name: Provision AWS Organization

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Type 'PROVISION' to confirm this action"
        required: true
        default: ""

env: 
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}

defaults: 
    run:
        shell: bash
        working-directory: "./aws-org"

jobs:
  provision-aws-org:
    name: Provision AWS Organization
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Validate Confirmation
        id: validate_confirmation
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "PROVISION" ]; then
            echo "Error: You must type 'PROVISION' to confirm this action."
            exit 1
          fi

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Deploy Infrastructure
        run: terraform apply -auto-approve
